

name: Test integrity

on: [ pull_request ]

jobs:

  test_integrity:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - run: |
          gcc testpullreq/test.c testpullreq/main.c -o test.out &&
          ./test.out &&
          echo $?


